Updates

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -17,10 +17,15 @@ jobs:
       run: npm install
 
     - name: Build project
-      run: npm run build
+      run: |
+        set -e
+        npm run build
+    
+    - name: Check build log
+      run: cat .next/build-manifest.json || echo "Build manifest not found"
 
     - name: Check dist folder exists
-      run: ls -la dist
+      run: ls -la out
 
     - name: Deploy to Lightsail
       uses: appleboy/scp-action@v0.1.6
@@ -31,6 +36,6 @@ jobs:
         port: 22
         debug: true  # Enable verbose output
         timeout: 30s
-        source: "dist"
+        source: "."
         target: "/var/www/html/eyeblobs/app"
         strip_components: 1  
